/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* src = "alu.v:1.1-15.10" *)
module alu(a, b, sel, result);
  (* src = "alu.v:2.21-2.22" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "alu.v:3.21-3.22" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "alu.v:4.21-4.24" *)
  input sel;
  wire sel;
  (* src = "alu.v:5.21-5.27" *)
  output [1:0] result;
  wire [1:0] result;
  wire _0_;
  wire _1_;
  wire _2_;
  XOR2X1 _3_ (
    .A(a[0]),
    .B(b[0]),
    .Y(result[0])
  );
  OAI21X1 _4_ (
    .A(a[0]),
    .B(sel),
    .C(b[0]),
    .Y(_2_)
  );
  AOI21X1 _5_ (
    .A(a[0]),
    .B(sel),
    .C(_2_),
    .Y(_0_)
  );
  XNOR2X1 _6_ (
    .A(a[1]),
    .B(b[1]),
    .Y(_1_)
  );
  XNOR2X1 _7_ (
    .A(_0_),
    .B(_1_),
    .Y(result[1])
  );
endmodule

(* src = "counter.v:1.1-13.10" *)
module counter(clk, rst, count);
  (* src = "counter.v:2.15-2.18" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.15-3.18" *)
  input rst;
  wire rst;
  (* src = "counter.v:4.21-4.26" *)
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  INVX1 _11_ (
    .A(count[3]),
    .Y(_04_)
  );
  INVX1 _12_ (
    .A(rst),
    .Y(_05_)
  );
  AND2X1 _13_ (
    .A(count[1]),
    .B(count[0]),
    .Y(_06_)
  );
  NAND3X1 _14_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .Y(_07_)
  );
  OAI21X1 _15_ (
    .A(count[2]),
    .B(_06_),
    .C(_05_),
    .Y(_08_)
  );
  AOI21X1 _16_ (
    .A(count[2]),
    .B(_06_),
    .C(_08_),
    .Y(_00_)
  );
  OAI21X1 _17_ (
    .A(count[1]),
    .B(count[0]),
    .C(_05_),
    .Y(_09_)
  );
  NOR2X1 _18_ (
    .A(_06_),
    .B(_09_),
    .Y(_01_)
  );
  NOR2X1 _19_ (
    .A(count[0]),
    .B(rst),
    .Y(_02_)
  );
  OAI21X1 _20_ (
    .A(_04_),
    .B(_07_),
    .C(_05_),
    .Y(_10_)
  );
  AOI21X1 _21_ (
    .A(_04_),
    .B(_07_),
    .C(_10_),
    .Y(_03_)
  );
  (* src = "counter.v:7.2-12.5" *)
  DFFPOSX1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[0])
  );
  (* src = "counter.v:7.2-12.5" *)
  DFFPOSX1 _23_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  (* src = "counter.v:7.2-12.5" *)
  DFFPOSX1 _24_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[2])
  );
  (* src = "counter.v:7.2-12.5" *)
  DFFPOSX1 _25_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule

(* top =  1  *)
(* src = "mini_soc.v:1.1-18.10" *)
module mini_soc(clk, rst, alu_sel, mux_sel, soc_out);
  (* src = "mini_soc.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "mini_soc.v:3.9-3.12" *)
  input rst;
  wire rst;
  (* src = "mini_soc.v:4.9-4.16" *)
  input alu_sel;
  wire alu_sel;
  (* src = "mini_soc.v:5.9-5.16" *)
  input mux_sel;
  wire mux_sel;
  (* src = "mini_soc.v:6.16-6.23" *)
  output [1:0] soc_out;
  wire [1:0] soc_out;
  (* src = "mini_soc.v:10.13-10.20" *)
  wire [1:0] alu_out;
  (* src = "mini_soc.v:9.13-9.18" *)
  wire [3:0] count;
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:15.6-15.77" *)
  alu u_alu (
    .a(count[3:2]),
    .b(count[1:0]),
    .result(alu_out),
    .sel(alu_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:13.10-13.57" *)
  counter u_counter (
    .clk(clk),
    .count(count),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:17.6-17.75" *)
  mux u_mux (
    .in0(count[3:2]),
    .in1(alu_out),
    .out(soc_out),
    .sel(mux_sel)
  );
endmodule

(* src = "mux.v:1.1-10.10" *)
module mux(in0, in1, sel, out);
  (* src = "mux.v:3.21-3.24" *)
  input [1:0] in0;
  wire [1:0] in0;
  (* src = "mux.v:4.21-4.24" *)
  input [1:0] in1;
  wire [1:0] in1;
  (* src = "mux.v:5.21-5.24" *)
  input sel;
  wire sel;
  (* src = "mux.v:6.21-6.24" *)
  output [1:0] out;
  wire [1:0] out;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  INVX1 _4_ (
    .A(in0[0]),
    .Y(_2_)
  );
  INVX1 _5_ (
    .A(in0[1]),
    .Y(_3_)
  );
  NAND2X1 _6_ (
    .A(in1[0]),
    .B(sel),
    .Y(_0_)
  );
  OAI21X1 _7_ (
    .A(_2_),
    .B(sel),
    .C(_0_),
    .Y(out[0])
  );
  NAND2X1 _8_ (
    .A(sel),
    .B(in1[1]),
    .Y(_1_)
  );
  OAI21X1 _9_ (
    .A(sel),
    .B(_3_),
    .C(_1_),
    .Y(out[1])
  );
endmodule
